### ISSUE TITLE
服务端闪退

### ISSUE THREAD

**Issue by 105hbh** [lakwsh/l4d2_vomit_fix#2]
单人对抗的测试，在boomer喷吐后服务端无提示闪退
排除了所有插件问题，在仅安装该插件（code下的两个smx和两个txt）时同样复现，去掉后不会闪退
服务端版本2229
服务端启动的端口为27016

**Comment by 105hbh** [comment]
插件log无对此mod报错

**Comment by 105hbh** [comment]
插件log无对此插件报错

**Comment by lakwsh** [comment]
抱歉，没留意到这个issue。
如果问题还在的话，提供一下系统版本，以及把其中一个插件拿掉看一下

**Comment by 105hbh** [comment]
> 抱歉，没留意到这个issue。 如果问题还在的话，提供一下系统版本，以及把其中一个插件拿掉看一下

系统是windows10
平台的话可能不太准确
meta 1.11.0-dev+1148
sm 1.12.0.7041

**Comment by 105hbh** [comment]
> 抱歉，没留意到这个issue。 如果问题还在的话，提供一下系统版本，以及把其中一个插件拿掉看一下



> 抱歉，没留意到这个issue。 如果问题还在的话，提供一下系统版本，以及把其中一个插件拿掉看一下

问题定位在l4d2_vomit_fix.smx 去掉l4d2_vomit_fix.txt之后是不闪退的，同时也不起作用

**Comment by lakwsh** [comment]
最新版smx和txt在游戏版本2239下还有问题吗

**Comment by 105hbh** [comment]
> 最新版smx和txt在游戏版本2239下还有问题吗

暂时还不清楚最新的2239，因为插件问题留在了2237。刚刚更新文件测试了下2237，问题依旧

**Comment by lakwsh** [comment]
已修复
