### ISSUE TITLE
Signature broken - 签名损坏

### ISSUE THREAD

**Issue by 105hbh** [lakwsh/l4d2_vomit_fix#3]
情况与上次同理，仅安装该插件时候依然报错(已安装l4dtoolz)

报错时版本信息
Linux steam 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
SourceMod Version: 1.12.0.7134
Metamod:Source version 1.12.0-dev+1210
Version 2.2.4.1 (left4dead2)

error.log
L 09/01/2024 - 21:58:29: SourceMod error session started
L 09/01/2024 - 21:58:29: Info (map "c2m2_fairgrounds") (file "/home/steam/Steam/steamapps/common/l4d2/left4dead2/addons/sourcemod/logs/errors_20240901.log")
L 09/01/2024 - 21:58:29: [SM] Failed to load plugin "nextmap.smx": Nextmap is incompatible with this game.
L 09/01/2024 - 21:58:29: [SM] Exception reported: 'a2s_fix' Signature broken.
L 09/01/2024 - 21:58:29: [SM] Blaming: l4d2_a2s_fix.smx
L 09/01/2024 - 21:58:29: [SM] Call stack trace:
L 09/01/2024 - 21:58:29: [SM]   [0] SetFailState
L 09/01/2024 - 21:58:29: [SM]   [1] Line 24, l4d2_a2s_fix.sp::OnPluginStart
L 09/01/2024 - 21:58:29: [SM] Unable to load plugin "l4d2_a2s_fix.smx": Error detected in plugin startup (see error logs)

**Comment by NeoMika** [comment]
我这里没报错，查服机器人的结果均是服务器无响应，移除这个插件就能查询到

**Comment by lakwsh** [comment]
已修
